version: '2.0'
services:
  server:
    image: node:alpine               
    command: sh -c 'echo "fooo" && yarn install && yarn run start.dev'


    working_dir: /opt/server
    volumes:
      - ./server/:/opt/server  
    ports:
      - "5000:5000"
    networks:
      dev-network:
        aliases:
          - server.local
  client:
    image: node:latest              
#    command: sh -c 'npm install --save-dev;ls; pwd; npm run serve'
    command: sh -c 'yarn install ; yarn run serve'

#    command: sh -c 'npm install  --save-dev; npm install --save axios; npm install -g nodemon; ls . ; nodemon src/main.js'
    working_dir: /opt/client
    volumes:
      - ./client:/opt/client
    ports:
      - "8080:8080"
      - "8000:8000"
    networks:
      dev-network:
        aliases:
          - client.local
  database:
    image: mongo:latest
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    ports:
      - 27017:27017
    environment:    
      - MONGODB_USERNAME=mongo
      - MONGODB_PASSWORD=mongo
      - MONGODB_DATABASE=DB
    networks:
      dev-network:
        aliases:
          - db.local
networks:
  dev-network:
    driver: bridge
volumes:
  mongodb:
  mongodb_config: